//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iseu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int StudentId { get; set; }
        public int SubjectId { get; set; }
        public Nullable<int> Note1 { get; set; }
    
        public virtual Subject Subject { get; set; }
    }
}
