//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iseu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public Professor()
        {
            this.Subjects = new HashSet<Subject>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ADegree { get; set; }
        public Nullable<int> ATitle { get; set; }
        public Nullable<int> ChairId { get; set; }
    
        public virtual ADegree ADegree1 { get; set; }
        public virtual ATitle ATitle1 { get; set; }
        public virtual Chair Chair { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
