//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iseu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Parents = new HashSet<Parent>();
        }
    
        public int Id { get; set; }
        public Nullable<int> EntryYear { get; set; }
        public Nullable<int> GraduationYear { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Characteristic { get; set; }
        public Nullable<System.DateTime> DateClaim { get; set; }
        public string PersonalNumber { get; set; }
        public Nullable<int> Competition { get; set; }
        public Nullable<int> EduGraduationYear { get; set; }
        public Nullable<int> EduType { get; set; }
        public string Concessions { get; set; }
        public Nullable<int> PreUniversityCourses { get; set; }
        public Nullable<int> Hostel { get; set; }
        public Nullable<int> CountClaim { get; set; }
        public string Language { get; set; }
        public Nullable<int> CertificatePoints { get; set; }
        public Nullable<int> LanguagePoints { get; set; }
        public Nullable<int> PhysicsPoints { get; set; }
        public Nullable<int> MathematicaPoints { get; set; }
        public Nullable<int> ChemistryPoints { get; set; }
        public Nullable<int> BiologyPoints { get; set; }
        public string InfoFrom { get; set; }
        public string PrioritySpecialities { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual User User { get; set; }
    }
}
