//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iseu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Notes = new HashSet<Note>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ChairId { get; set; }
        public string Title { get; set; }
    
        public virtual Chair Chair { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
    }
}
