//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iseu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Syllabus
    {
        public Syllabus()
        {
            this.Specialities = new HashSet<Speciality>();
        }
    
        public int Id { get; set; }
        public string Syllabus1 { get; set; }
    
        public virtual ICollection<Speciality> Specialities { get; set; }
    }
}
